### ISSUE TITLE
Add an example for the neodymium xcmailr plugin

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-showcase#11]
We will write a simple plugin to use the XCMailr together with Neodymium.
Once this is done we need to showcase the usage of this plugin.

1. Showcase the following things
  - [x] Configuration of the plugin
  - [x] Creation of a temporary mailbox/email
  - [x] Retrieval of emails
  - [x] Download of the email content and displaying it in a browser tab (use Selenide to validate  the email content)
  - [x] Deletion of a temporary mailbox/email (if it is available until then)

2. Showcase other useful aspects of the API (discuss with the team what could be needed)

3. Documentation (in neodymium library wiki)
  - [ ] Document the restrictions of our xcmailr instance (only specific domains), but it can be self hosted link to the documentation of the xcmailr github project.
  - [ ] Retrieval of the API key from the website (needed every 30 days at the moment)
  - [ ] Usage of our plugin API functionalities

**Comment by occupant23** [comment]
@georgkunze please introduce @jseng92 to the missing parts of this task.
Document the state of the task within this issue.

**Comment by georgkunze** [comment]
@jseng92 The first comment of this issue is up to date. The basic usage of the xcmailr plugin is already shown in BasiXcMailrTest. The documentation within the testcases is done and i added a section to the README.md.
What needs to be done is showing other useful aspects of the api(Point 2) and a the documentation in the wiki(Point 3).
