### ISSUE TITLE
Add a basic authentication example

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-showcase#13]
Add a short tests that shows the basic test setup for pages using basic auth.

` Selenide.open(url, "", Neodymium.configuration().basicAuthUsername(), Neodymium.configuration().basicAuthPassword());`

DemoPage: http://www.httpwatch.com/httpgallery/authentication/authenticatedimage/default.aspx?0.7349707232788205
User: httpwatch
Password: foo

**Comment by georgkunze** [comment]
Reworked the tests into 3 seperate testclasses. Testclasses now use a temporary neodymium.properties file to avoid setting up and tearing down the webdriver. The Problem is now that all tests run after those tests have a proxy error. Might be due to settings not correctly resetting. (temporary file is deleted at the end)

@ckeiner @oomelianchuk @rklehm-xc fyi
